/**
 * Job Workspace — /workspace/:id
 *
 * Fixes in this version:
 * 1. ATS = 0 bug: was checking `!job.atsScore` which is falsy for 0 → now checks `job.atsScore == null`
 * 2. Cover letter visibility: handleJobUpdate now deep-merges nested objects
 * 3. Skill gap visibility: condition now correctly shows results when arrays exist (even empty)
 * 4. PDF download for tailored resume and cover letter
 * 5. All tabs show proper empty states with clear CTAs
 */
import { useState, useEffect, useRef, useCallback } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import {
  LayoutDashboard, Upload, Target, TrendingUp, FileText,
  BookOpen, HelpCircle, Loader2, CheckCircle, AlertCircle,
  Copy, RefreshCw, ArrowRight, ChevronLeft, Zap, Download,
} from 'lucide-react';
import DashboardLayout from '../components/dashboard/DashboardLayout';
import api from '../services/api';
import toast from 'react-hot-toast';
import { pdf } from '@react-pdf/renderer';

/* ── Tab config ─────────────────────────────────────────────────────────── */
const TABS = [
  { id: 'overview',    label: 'Overview',     icon: LayoutDashboard },
  { id: 'resume',      label: 'Resume',        icon: Upload          },
  { id: 'ats',         label: 'ATS Score',     icon: Target          },
  { id: 'skills',      label: 'Skill Gap',     icon: TrendingUp      },
  { id: 'tailor',      label: 'Tailor Resume', icon: FileText        },
  { id: 'coverletter', label: 'Cover Letter',  icon: BookOpen        },
  { id: 'quiz',        label: 'Quiz',          icon: HelpCircle      },
];

/* ── Helpers ─────────────────────────────────────────────────────────────── */
const scoreColor = (s) =>
  s == null ? 'text-nb-black/30'
  : s >= 80  ? 'text-green-700'
  : s >= 60  ? 'text-amber-700'
  :             'text-red-700';

const scoreBg = (s) =>
  s == null ? ''
  : s >= 80  ? 'bg-green-50 border-green-300'
  : s >= 60  ? 'bg-amber-50 border-amber-300'
  :             'bg-red-50 border-red-300';

/* ── Download plain-text cover letter ──────────────────────────────────── */
const downloadTextFile = (text, filename) => {
  const blob = new Blob([text], { type: 'text/plain' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
};

/* ── Download tailored resume as PDF ───────────────────────────────────── */
const downloadTailoredResumePDF = async (text, jobTitle) => {
  // Import lazily to avoid loading @react-pdf/renderer until needed
  const { Document, Page, Text, View, StyleSheet, pdf: pdfRenderer } = await import('@react-pdf/renderer');

  const styles = StyleSheet.create({
    page:    { fontFamily: 'Helvetica', fontSize: 10, color: '#111', padding: 40, lineHeight: 1.5 },
    title:   { fontSize: 14, fontFamily: 'Helvetica-Bold', marginBottom: 16, letterSpacing: -0.3 },
    content: { fontSize: 10, lineHeight: 1.6, whiteSpace: 'pre-wrap' },
    footer:  { position: 'absolute', bottom: 20, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#999', borderTopWidth: 0.5, borderTopColor: '#ddd', paddingTop: 6 },
  });

  const doc = (
    <Document title={`Tailored Resume — ${jobTitle || 'Resume'}`}>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Tailored Resume — {jobTitle || 'Position'}</Text>
        <Text style={styles.content}>{text}</Text>
        <Text style={styles.footer} fixed>Generated by CrackIt AI · crackiitai.vercel.app</Text>
      </Page>
    </Document>
  );

  const blob = await pdfRenderer(doc).toBlob();
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `Tailored_Resume_${(jobTitle || 'Job').replace(/\s+/g, '_')}.pdf`;
  a.click();
  URL.revokeObjectURL(url);
};

/* ── Score ring (SVG) ───────────────────────────────────────────────────── */
const ScoreRing = ({ score, label, size = 80 }) => {
  const r     = (size / 2) - 8;
  const circ  = 2 * Math.PI * r;
  const pct   = score != null ? Math.min(score, 100) / 100 : 0;
  const dash  = circ * pct;
  const color = score == null ? '#ddd'
    : score >= 80 ? '#1A7A4A'
    : score >= 60 ? '#D97706'
    : '#DC2626';
  return (
    <div className="flex flex-col items-center gap-1">
      <svg width={size} height={size} style={{ transform: 'rotate(-90deg)' }}>
        <circle cx={size/2} cy={size/2} r={r} fill="none" stroke="#e5e7eb" strokeWidth="6" />
        <circle cx={size/2} cy={size/2} r={r} fill="none" stroke={color} strokeWidth="6"
          strokeDasharray={`${dash} ${circ}`} strokeLinecap="round" />
        <text x="50%" y="50%" dominantBaseline="middle" textAnchor="middle"
          style={{ transform: 'rotate(90deg)', transformOrigin: '50% 50%',
            fontSize: size < 70 ? 13 : 17, fontWeight: 900, fill: color, fontFamily: 'var(--font-mono)' }}>
          {score != null ? score : '—'}
        </text>
      </svg>
      <span className="text-[10px] font-black uppercase tracking-widest text-nb-black/45">{label}</span>
    </div>
  );
};

const ActionBtn = ({ onClick, loading, disabled, children, variant = 'primary', className = '' }) => (
  <button
    onClick={onClick}
    disabled={loading || disabled}
    className={`btn ${variant === 'primary' ? 'btn-primary' : 'btn-ghost'} ${loading || disabled ? 'opacity-50 cursor-not-allowed' : ''} ${className}`}
  >
    {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : children}
  </button>
);

const CopyBtn = ({ text }) => {
  const [copied, setCopied] = useState(false);
  const handle = () => {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      toast.success('Copied to clipboard!');
      setTimeout(() => setCopied(false), 2000);
    });
  };
  return (
    <button onClick={handle} className="btn btn-ghost btn-sm">
      {copied ? <><CheckCircle className="w-3.5 h-3.5" /> Copied!</> : <><Copy className="w-3.5 h-3.5" /> Copy</>}
    </button>
  );
};

/* ═══════════════════════════════════════════════════════════════════════════
   TAB COMPONENTS
═══════════════════════════════════════════════════════════════════════════ */

/* ── Overview ──────────────────────────────────────────────────────────── */
function OverviewTab({ job, onTabChange }) {
  const steps = [
    { id: 'resume',      label: 'Resume uploaded',  done: !!(job.resumeText || job.parsedResume?.name) },
    { id: 'ats',         label: 'ATS score run',     done: job.atsScore != null },
    { id: 'skills',      label: 'Skill gap done',    done: !!(job.skillGap?.have || job.skillGap?.missing) },
    { id: 'tailor',      label: 'Resume tailored',   done: !!job.tailoredResume?.text },
    { id: 'coverletter', label: 'Cover letter done', done: !!job.coverLetter?.text },
    { id: 'quiz',        label: 'Quiz generated',    done: (job.quiz?.questions?.length || 0) > 0 },
  ];
  const completed = steps.filter(s => s.done).length;

  return (
    <div className="space-y-6">
      {/* Scores */}
      <div className="bg-white border-2 border-nb-black p-6" style={{ borderRadius: '8px', boxShadow: '4px 4px 0 #111' }}>
        <p className="text-[11px] font-black uppercase tracking-widest text-nb-black/45 mb-5">Scores</p>
        <div className="flex flex-wrap gap-8 items-center">
          <ScoreRing score={job.atsScore}       label="ATS Match"     size={90} />
          <ScoreRing score={job.readinessScore} label="Job Readiness" size={90} />
          {job.quiz?.score != null && job.quiz?.totalQuestions > 0 && (
            <ScoreRing score={Math.round((job.quiz.score / job.quiz.totalQuestions) * 100)} label="Quiz Score" size={90} />
          )}
        </div>
      </div>

      {/* Progress checklist */}
      <div className="bg-white border-2 border-nb-black p-6" style={{ borderRadius: '8px', boxShadow: '4px 4px 0 #111' }}>
        <p className="text-[11px] font-black uppercase tracking-widest text-nb-black/45 mb-4">
          Progress — {completed}/{steps.length} complete
        </p>
        <div className="space-y-2">
          {steps.map(({ id, label, done }) => (
            <button
              key={id}
              onClick={() => onTabChange(id)}
              className="w-full flex items-center gap-3 py-2.5 px-3 border-2 border-nb-black/10 hover:border-nb-black hover:bg-nb-yellow/10 transition-colors text-left"
              style={{ borderRadius: '6px' }}
            >
              {done
                ? <CheckCircle className="w-4 h-4 text-green-600 flex-shrink-0" />
                : <div className="w-4 h-4 border-2 border-nb-black/30 rounded-full flex-shrink-0" />}
              <span className={`text-sm font-bold flex-1 ${done ? 'line-through text-nb-black/40' : ''}`}>{label}</span>
              <ArrowRight className="w-3.5 h-3.5 text-nb-black/20" />
            </button>
          ))}
        </div>
      </div>

      {/* Top recommendations */}
      {job.atsRecommendations?.length > 0 && (
        <div className="bg-nb-yellow border-2 border-nb-black p-5" style={{ borderRadius: '8px', boxShadow: '3px 3px 0 #111' }}>
          <p className="text-[11px] font-black uppercase tracking-widest mb-3">Top ATS Recommendations</p>
          <ul className="space-y-2">
            {job.atsRecommendations.slice(0, 5).map((r, i) => (
              <li key={i} className="flex gap-2 text-sm"><span className="font-black flex-shrink-0">→</span>{r}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

/* ── Resume Upload ──────────────────────────────────────────────────────── */
function ResumeTab({ job, onJobUpdate }) {
  const [uploading, setUploading] = useState(false);
  const fileRef = useRef(null);

  const handleFile = async (file) => {
    if (!file) return;
    const ext = file.name.split('.').pop().toLowerCase();
    if (!['pdf', 'doc', 'docx'].includes(ext)) {
      toast.error('Only PDF, DOC, DOCX supported'); return;
    }
    setUploading(true);
    const fd = new FormData();
    fd.append('resume', file);
    try {
      const { data } = await api.post(`/jobs/${job._id}/upload-resume`, fd, {
        headers: { 'Content-Type': 'multipart/form-data' },
        timeout: 90000,
      });
      onJobUpdate(data.data);
      toast.success('Resume uploaded and parsed!');
    } catch (err) {
      toast.error(err.response?.data?.message || 'Upload failed');
    } finally { setUploading(false); }
  };

  const hasResume = !!(job.resumeText || job.parsedResume?.name);

  return (
    <div className="space-y-6 max-w-2xl">
      <div
        className={`border-2 border-dashed p-12 text-center cursor-pointer transition-colors ${
          hasResume ? 'border-nb-black bg-nb-yellow/5' : 'border-nb-black/30 hover:border-nb-black hover:bg-nb-yellow/10'
        }`}
        style={{ borderRadius: '8px' }}
        onClick={() => fileRef.current?.click()}
        onDragOver={e => e.preventDefault()}
        onDrop={e => { e.preventDefault(); handleFile(e.dataTransfer.files[0]); }}
      >
        <input ref={fileRef} type="file" className="hidden" accept=".pdf,.doc,.docx"
          onChange={e => handleFile(e.target.files[0])} />
        {uploading ? (
          <>
            <Loader2 className="w-10 h-10 animate-spin mx-auto mb-3 text-nb-black/40" />
            <p className="font-black text-sm">Parsing resume with AI…</p>
            <p className="text-xs text-nb-black/40 mt-1">This may take 10–30 seconds</p>
          </>
        ) : (
          <>
            <Upload className={`w-10 h-10 mx-auto mb-3 ${hasResume ? 'text-nb-black/50' : 'text-nb-black/25'}`} />
            <p className="font-black text-sm uppercase tracking-wide">
              {hasResume ? 'Re-upload resume' : 'Drop resume here or click to upload'}
            </p>
            <p className="text-xs text-nb-black/40 mt-1">PDF, DOC, DOCX — max 5 MB</p>
          </>
        )}
      </div>

      {hasResume && (
        <div className="bg-white border-2 border-nb-black p-5 space-y-4" style={{ borderRadius: '8px', boxShadow: '3px 3px 0 #111' }}>
          <div className="flex items-center gap-2 border-b-2 border-nb-black/10 pb-3">
            <CheckCircle className="w-4 h-4 text-green-600" />
            <p className="font-black text-sm uppercase tracking-wide">Resume Parsed</p>
            {job.resumeFileName && <span className="text-xs text-nb-black/35 font-mono ml-auto">{job.resumeFileName}</span>}
          </div>
          <div className="grid sm:grid-cols-2 gap-3 text-sm">
            {job.parsedResume?.name && (
              <div><span className="nb-label">Name</span><p className="font-bold">{job.parsedResume.name}</p></div>
            )}
            {job.parsedResume?.email && (
              <div><span className="nb-label">Email</span><p className="font-bold">{job.parsedResume.email}</p></div>
            )}
            <div><span className="nb-label">Skills found</span><p className="font-bold text-lg">{job.parsedResume?.skills?.length || 0}</p></div>
            <div><span className="nb-label">Experience entries</span><p className="font-bold text-lg">{job.parsedResume?.experience?.length || 0}</p></div>
          </div>
          {job.parsedResume?.skills?.length > 0 && (
            <div>
              <span className="nb-label">Skills</span>
              <div className="flex flex-wrap gap-1.5 mt-2">
                {job.parsedResume.skills.slice(0, 25).map(s => (
                  <span key={s} className="text-[11px] font-bold px-2 py-0.5 bg-[#F5F1E8] border-2 border-nb-black/20" style={{ borderRadius: '3px' }}>{s}</span>
                ))}
                {job.parsedResume.skills.length > 25 && (
                  <span className="text-[11px] text-nb-black/40">+{job.parsedResume.skills.length - 25} more</span>
                )}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

/* ── ATS Score ──────────────────────────────────────────────────────────── */
function ATSTab({ job, onJobUpdate }) {
  const [loading, setLoading] = useState(false);

  const run = async () => {
    setLoading(true);
    try {
      const { data } = await api.post(`/jobs/${job._id}/ats-score`);
      onJobUpdate(data.data);
      toast.success('ATS score calculated!');
    } catch (err) {
      toast.error(err.response?.data?.message || 'ATS calculation failed');
    } finally { setLoading(false); }
  };

  const hasResume = !!(job.resumeText || job.parsedResume?.name);
  const hasScore  = job.atsScore != null;  // FIX: was `!job.atsScore` which broke on score=0

  if (!hasScore) return (
    <div className="max-w-md space-y-4">
      <p className="text-sm text-nb-black/60 leading-relaxed">
        Calculate how well your resume matches the job description. The AI performs semantic matching — not just keyword counting.
      </p>
      <ActionBtn onClick={run} loading={loading} disabled={!hasResume}>
        <Target className="w-4 h-4" /> Calculate ATS Score
      </ActionBtn>
      {!hasResume && (
        <div className="flex items-center gap-2 p-3 bg-amber-50 border-2 border-amber-300 text-xs font-bold text-amber-800" style={{ borderRadius: '6px' }}>
          <AlertCircle className="w-4 h-4 flex-shrink-0" />
          Go to the Resume tab and upload your resume first.
        </div>
      )}
    </div>
  );

  const breakdown = job.atsBreakdown || {};

  return (
    <div className="space-y-6 max-w-2xl">

      {/* Score hero */}
      <div className={`border-2 border-nb-black p-6 flex items-center gap-6 ${scoreBg(job.atsScore)}`} style={{ borderRadius: '8px', boxShadow: '4px 4px 0 #111' }}>
        <ScoreRing score={job.atsScore} label="ATS Match" size={100} />
        <div className="flex-1 space-y-2">
          <p className={`text-4xl font-black font-mono ${scoreColor(job.atsScore)}`}>{job.atsScore}<span className="text-xl">/100</span></p>
          <p className="text-sm font-bold text-nb-black/60">
            {job.atsScore >= 80 ? '✅ Strong match — good chances of passing ATS filters.'
             : job.atsScore >= 60 ? '⚠️ Moderate match — some gaps to address.'
             : job.atsScore >= 40 ? '⚠️ Weak match — significant improvements needed.'
             : '❌ Poor match — resume needs major rework for this role.'}
          </p>
          <ActionBtn onClick={run} loading={loading} variant="ghost">
            <RefreshCw className="w-3.5 h-3.5" /> Re-run
          </ActionBtn>
        </div>
      </div>

      {/* Score breakdown bars */}
      {Object.keys(breakdown).length > 0 && (
        <div className="bg-white border-2 border-nb-black p-5" style={{ borderRadius: '8px', boxShadow: '3px 3px 0 #111' }}>
          <p className="text-[11px] font-black uppercase tracking-widest mb-4">Score Breakdown</p>
          <div className="space-y-3.5">
            {Object.entries(breakdown).map(([k, v]) => {
              const barColor = v >= 80 ? 'bg-green-500' : v >= 60 ? 'bg-amber-400' : 'bg-red-500';
              return (
                <div key={k}>
                  <div className="flex justify-between text-xs font-bold mb-1.5">
                    <span className="uppercase tracking-wide text-nb-black/60">{k.replace(/([A-Z])/g, ' $1').trim()}</span>
                    <span className={`font-mono ${v >= 80 ? 'text-green-700' : v >= 60 ? 'text-amber-700' : 'text-red-600'}`}>{v}%</span>
                  </div>
                  <div className="h-2.5 border-2 border-nb-black bg-[#F5F1E8]">
                    <div className={`h-full ${barColor} border-r-2 border-nb-black transition-all duration-700`} style={{ width: `${Math.max(v, 0)}%` }} />
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Strong matches / Missing skills */}
      <div className="grid sm:grid-cols-2 gap-4">
        {job.atsStrongMatches?.length > 0 && (
          <div className="bg-green-50 border-2 border-green-300 p-4" style={{ borderRadius: '6px', boxShadow: '3px 3px 0 #166534' }}>
            <p className="text-[10px] font-black uppercase tracking-widest text-green-800 mb-3">✓ Strong Matches ({job.atsStrongMatches.length})</p>
            <ul className="space-y-1.5">
              {job.atsStrongMatches.map((m, i) => (
                <li key={i} className="text-xs text-green-800 flex gap-1.5 items-start">
                  <CheckCircle className="w-3.5 h-3.5 flex-shrink-0 mt-0.5" />{m}
                </li>
              ))}
            </ul>
          </div>
        )}
        {job.atsMissingSkills?.length > 0 && (
          <div className="bg-red-50 border-2 border-red-300 p-4" style={{ borderRadius: '6px', boxShadow: '3px 3px 0 #991b1b' }}>
            <p className="text-[10px] font-black uppercase tracking-widest text-red-800 mb-3">✕ Missing Skills ({job.atsMissingSkills.length})</p>
            <ul className="space-y-1.5">
              {job.atsMissingSkills.map((m, i) => (
                <li key={i} className="text-xs text-red-800 flex gap-1.5 items-start">
                  <AlertCircle className="w-3.5 h-3.5 flex-shrink-0 mt-0.5" />{m}
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>

      {/* Weak matches */}
      {job.atsWeakMatches?.length > 0 && (
        <div className="bg-amber-50 border-2 border-amber-300 p-4" style={{ borderRadius: '6px' }}>
          <p className="text-[10px] font-black uppercase tracking-widest text-amber-800 mb-3">⚠ Weak Matches — Needs Strengthening</p>
          <div className="flex flex-wrap gap-2">
            {job.atsWeakMatches.map((m, i) => (
              <span key={i} className="text-xs font-bold px-2 py-1 bg-amber-100 text-amber-800 border border-amber-300" style={{ borderRadius: '3px' }}>{m}</span>
            ))}
          </div>
        </div>
      )}

      {/* Recommendations */}
      {job.atsRecommendations?.length > 0 && (
        <div className="bg-nb-yellow border-2 border-nb-black p-5" style={{ borderRadius: '6px', boxShadow: '3px 3px 0 #111' }}>
          <p className="text-[11px] font-black uppercase tracking-widest mb-3">Recommendations</p>
          <ul className="space-y-2">
            {job.atsRecommendations.map((r, i) => (
              <li key={i} className="text-sm flex gap-2 items-start">
                <span className="font-black flex-shrink-0 mt-0.5">→</span>{r}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

/* ── Skill Gap ──────────────────────────────────────────────────────────── */
function SkillsTab({ job, onJobUpdate }) {
  const [loading, setLoading] = useState(false);

  const run = async () => {
    setLoading(true);
    try {
      const { data } = await api.post(`/jobs/${job._id}/skill-gap`);
      onJobUpdate(data.data);
      toast.success('Skill gap analysed!');
    } catch (err) {
      toast.error(err.response?.data?.message || 'Skill gap analysis failed');
    } finally { setLoading(false); }
  };

  const importanceStyles = {
    critical: 'bg-red-100 text-red-800 border-red-300',
    high:     'bg-orange-100 text-orange-800 border-orange-300',
    medium:   'bg-amber-50 text-amber-800 border-amber-300',
    low:      'bg-gray-100 text-gray-600 border-gray-300',
  };

  // FIX: was `!gap?.missing && !gap?.have` which broke when arrays were present but empty
  // Now shows the analysis view whenever skillGap object exists at all
  const gap        = job.skillGap;
  const hasRun     = gap != null && typeof gap === 'object' && ('have' in gap || 'missing' in gap || 'improve' in gap || 'niceToHave' in gap);
  const hasResume  = !!(job.resumeText || job.parsedResume?.name);

  if (!hasRun) return (
    <div className="max-w-md space-y-4">
      <p className="text-sm text-nb-black/60 leading-relaxed">
        Compare your skills against the job requirements. The AI categorises each skill as something you have, need to improve, or are missing entirely.
      </p>
      <ActionBtn onClick={run} loading={loading} disabled={!hasResume}>
        <TrendingUp className="w-4 h-4" /> Analyse Skill Gap
      </ActionBtn>
      {!hasResume && (
        <div className="flex items-center gap-2 p-3 bg-amber-50 border-2 border-amber-300 text-xs font-bold text-amber-800" style={{ borderRadius: '6px' }}>
          <AlertCircle className="w-4 h-4 flex-shrink-0" />
          Upload your resume first (Resume tab).
        </div>
      )}
    </div>
  );

  const SkillSection = ({ title, bg, border, shadow, items, showWhy }) => {
    if (!items?.length) return null;
    return (
      <div className={`border-2 p-5 ${bg} ${border}`} style={{ borderRadius: '6px', boxShadow: shadow || '3px 3px 0 #111' }}>
        <p className="text-[11px] font-black uppercase tracking-widest mb-3">{title} ({items.length})</p>
        <div className="space-y-2.5">
          {items.map((item, i) => {
            const skill = typeof item === 'string' ? item : item.skill;
            const imp   = typeof item === 'string' ? null : item.importance;
            const why   = typeof item === 'string' ? null : item.why;
            return (
              <div key={i} className="flex items-start gap-2">
                {imp && (
                  <span className={`text-[9px] font-black px-1.5 py-0.5 border flex-shrink-0 mt-0.5 capitalize ${importanceStyles[imp] || importanceStyles.low}`} style={{ borderRadius: '2px' }}>
                    {imp}
                  </span>
                )}
                <div>
                  <span className="text-sm font-bold">{skill}</span>
                  {showWhy && why && <p className="text-xs text-nb-black/50 mt-0.5 leading-relaxed">{why}</p>}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    );
  };

  const totalHave    = gap.have?.length    || 0;
  const totalMissing = gap.missing?.length || 0;
  const coverage     = totalHave + totalMissing > 0 ? Math.round((totalHave / (totalHave + totalMissing)) * 100) : 0;

  return (
    <div className="space-y-5 max-w-2xl">
      {/* Summary bar */}
      <div className="bg-white border-2 border-nb-black p-4 flex items-center gap-4" style={{ borderRadius: '8px', boxShadow: '3px 3px 0 #111' }}>
        <div className="flex-1">
          <div className="flex justify-between text-xs font-bold mb-1.5">
            <span className="uppercase tracking-wide text-nb-black/60">Skill Coverage</span>
            <span className="font-mono">{coverage}%</span>
          </div>
          <div className="h-3 border-2 border-nb-black bg-[#F5F1E8]">
            <div className={`h-full border-r-2 border-nb-black ${coverage >= 70 ? 'bg-green-500' : coverage >= 50 ? 'bg-amber-400' : 'bg-red-500'}`}
              style={{ width: `${coverage}%` }} />
          </div>
          <p className="text-[10px] text-nb-black/40 mt-1">{totalHave} matched · {totalMissing} missing · {gap.improve?.length || 0} to improve</p>
        </div>
        <ActionBtn onClick={run} loading={loading} variant="ghost">
          <RefreshCw className="w-3.5 h-3.5" /> Re-run
        </ActionBtn>
      </div>

      <SkillSection title="✓ Already Have"     bg="bg-green-50"   border="border-green-300"  shadow="3px 3px 0 #166534" items={gap.have}       showWhy={false} />
      <SkillSection title="⚠ Need to Improve"  bg="bg-amber-50"   border="border-amber-300"  shadow="3px 3px 0 #92400e" items={gap.improve}    showWhy={true} />
      <SkillSection title="✕ Missing"           bg="bg-red-50"     border="border-red-300"    shadow="3px 3px 0 #991b1b" items={gap.missing}    showWhy={true} />
      <SkillSection title="★ Nice to Have"      bg="bg-[#F5F1E8]" border="border-nb-black/20" shadow="3px 3px 0 #111"   items={gap.niceToHave} showWhy={false} />

      {!gap.have?.length && !gap.missing?.length && !gap.improve?.length && (
        <div className="p-4 bg-amber-50 border-2 border-amber-300 text-sm text-amber-800" style={{ borderRadius: '6px' }}>
          The AI couldn't extract enough skill data. Try re-running after ensuring the resume and JD were properly parsed.
        </div>
      )}
    </div>
  );
}

/* ── Tailor Resume ──────────────────────────────────────────────────────── */
function TailorTab({ job, onJobUpdate }) {
  const [loading,     setLoading]     = useState(false);
  const [downloading, setDownloading] = useState(false);

  const run = async () => {
    setLoading(true);
    try {
      const { data } = await api.post(`/jobs/${job._id}/tailor-resume`);
      onJobUpdate(data.data);
      toast.success('Resume tailored!');
    } catch (err) {
      toast.error(err.response?.data?.message || 'Tailoring failed');
    } finally { setLoading(false); }
  };

  const handleDownload = async () => {
    setDownloading(true);
    try {
      await downloadTailoredResumePDF(job.tailoredResume.text, job.title);
      toast.success('PDF downloaded!');
    } catch (err) {
      toast.error('PDF generation failed');
      console.error(err);
    } finally { setDownloading(false); }
  };

  const hasResume  = !!(job.resumeText || job.parsedResume?.name);
  const tailored   = job.tailoredResume;

  if (!tailored?.text) return (
    <div className="max-w-md space-y-4">
      <div className="bg-nb-yellow border-2 border-nb-black p-4" style={{ borderRadius: '6px' }}>
        <p className="text-xs font-black mb-1.5 uppercase tracking-wide">Honesty Guarantee</p>
        <p className="text-xs text-nb-black/70 leading-relaxed">
          The AI improves your existing content for this JD — rewriting bullet points, highlighting relevant experience, adding JD keywords that legitimately apply. It will <strong>never</strong> fabricate skills, experience, or certifications.
        </p>
      </div>
      <ActionBtn onClick={run} loading={loading} disabled={!hasResume}>
        <FileText className="w-4 h-4" /> Tailor My Resume
      </ActionBtn>
      {!hasResume && (
        <div className="flex items-center gap-2 p-3 bg-amber-50 border-2 border-amber-300 text-xs font-bold text-amber-800" style={{ borderRadius: '6px' }}>
          <AlertCircle className="w-4 h-4 flex-shrink-0" />Upload your resume first (Resume tab).
        </div>
      )}
    </div>
  );

  return (
    <div className="space-y-5 max-w-2xl">
      {/* Actions */}
      <div className="flex items-center gap-3 flex-wrap">
        <ActionBtn onClick={run} loading={loading} variant="ghost">
          <RefreshCw className="w-3.5 h-3.5" /> Regenerate
        </ActionBtn>
        <CopyBtn text={tailored.text} />
        <button
          onClick={handleDownload}
          disabled={downloading}
          className="btn btn-primary btn-sm"
        >
          {downloading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Download className="w-3.5 h-3.5" />}
          Download PDF
        </button>
      </div>

      {/* Warnings */}
      {tailored.warnings?.length > 0 && (
        <div className="bg-amber-50 border-2 border-amber-400 p-4" style={{ borderRadius: '6px' }}>
          <p className="text-xs font-black text-amber-800 mb-2 uppercase tracking-wide">
            Missing Skills (NOT added — add manually if you have them)
          </p>
          <ul className="space-y-1">
            {tailored.warnings.map((w, i) => (
              <li key={i} className="text-xs text-amber-700 flex gap-1.5 items-start">
                <AlertCircle className="w-3.5 h-3.5 flex-shrink-0 mt-0.5" />{w}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Changes made */}
      {tailored.changes?.length > 0 && (
        <div className="bg-green-50 border-2 border-green-200 p-4" style={{ borderRadius: '6px' }}>
          <p className="text-[10px] font-black uppercase tracking-widest text-green-800 mb-2">Changes Made ({tailored.changes.length})</p>
          <ul className="space-y-1">
            {tailored.changes.map((c, i) => (
              <li key={i} className="text-xs text-green-800 flex gap-1.5">
                <span className="font-black flex-shrink-0">+</span>{c}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Resume text */}
      <div className="bg-white border-2 border-nb-black" style={{ borderRadius: '6px', boxShadow: '3px 3px 0 #111' }}>
        <div className="flex items-center justify-between px-4 py-3 border-b-2 border-nb-black">
          <p className="text-[10px] font-black uppercase tracking-widest">Tailored Resume</p>
          <span className="text-[10px] font-mono text-nb-black/30">{tailored.text.split(/\s+/).length} words</span>
        </div>
        <div className="p-5">
          <pre className="text-xs leading-relaxed text-nb-black/80 whitespace-pre-wrap font-mono overflow-auto max-h-[500px]">
            {tailored.text}
          </pre>
        </div>
      </div>
    </div>
  );
}

/* ── Cover Letter ──────────────────────────────────────────────────────── */
function CoverLetterTab({ job, onJobUpdate }) {
  const [loading,     setLoading]     = useState(false);
  const [downloading, setDownloading] = useState(false);

  const run = async () => {
    setLoading(true);
    try {
      const { data } = await api.post(`/jobs/${job._id}/cover-letter`);
      onJobUpdate(data.data);
      toast.success('Cover letter generated!');
    } catch (err) {
      toast.error(err.response?.data?.message || 'Cover letter generation failed');
    } finally { setLoading(false); }
  };

  const handleDownload = () => {
    setDownloading(true);
    try {
      downloadTextFile(
        job.coverLetter.text,
        `Cover_Letter_${(job.title || 'Job').replace(/\s+/g, '_')}.txt`
      );
      toast.success('Cover letter downloaded!');
    } catch {
      toast.error('Download failed');
    } finally { setDownloading(false); }
  };

  const hasResume = !!(job.resumeText || job.parsedResume?.name);
  // FIX: was using `cl` variable — now reads directly from job prop passed fresh each render
  const coverLetter = job.coverLetter;
  const hasLetter   = !!(coverLetter?.text);

  if (!hasLetter) return (
    <div className="max-w-md space-y-4">
      <p className="text-sm text-nb-black/60 leading-relaxed">
        Generate a professional, job-specific cover letter using your resume and the job description. It will be factual and tailored to the role.
      </p>
      <ActionBtn onClick={run} loading={loading} disabled={!hasResume}>
        <BookOpen className="w-4 h-4" /> Generate Cover Letter
      </ActionBtn>
      {!hasResume && (
        <div className="flex items-center gap-2 p-3 bg-amber-50 border-2 border-amber-300 text-xs font-bold text-amber-800" style={{ borderRadius: '6px' }}>
          <AlertCircle className="w-4 h-4 flex-shrink-0" /> Upload your resume first (Resume tab).
        </div>
      )}
    </div>
  );

  return (
    <div className="space-y-5 max-w-2xl">
      {/* Actions */}
      <div className="flex items-center gap-3 flex-wrap">
        <ActionBtn onClick={run} loading={loading} variant="ghost">
          <RefreshCw className="w-3.5 h-3.5" /> Regenerate
        </ActionBtn>
        <CopyBtn text={coverLetter.text} />
        <button onClick={handleDownload} disabled={downloading} className="btn btn-primary btn-sm">
          {downloading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Download className="w-3.5 h-3.5" />}
          Download .txt
        </button>
      </div>

      {/* Cover letter display */}
      <div className="bg-white border-2 border-nb-black" style={{ borderRadius: '6px', boxShadow: '3px 3px 0 #111' }}>
        <div className="flex items-center justify-between px-4 py-3 border-b-2 border-nb-black">
          <p className="text-[10px] font-black uppercase tracking-widest">Cover Letter</p>
          <span className="text-[10px] font-mono text-nb-black/30">{coverLetter.text.split(/\s+/).length} words</span>
        </div>
        <div className="p-6">
          <p className="text-sm leading-relaxed text-nb-black/80 whitespace-pre-wrap" style={{ fontFamily: 'Georgia, serif', lineHeight: '1.75' }}>
            {coverLetter.text}
          </p>
        </div>
      </div>
    </div>
  );
}

/* ── Quiz ────────────────────────────────────────────────────────────────── */
function QuizTab({ job, onJobUpdate, navigate }) {
  const [loading, setLoading] = useState(false);

  const generate = async () => {
    setLoading(true);
    try {
      const { data } = await api.post(`/jobs/${job._id}/generate-quiz`);
      onJobUpdate(data.data);
      const count = data.data?.quiz?.questions?.length || 0;
      toast.success(`${count} questions generated!`);
    } catch (err) {
      toast.error(err.response?.data?.message || 'Quiz generation failed');
    } finally { setLoading(false); }
  };

  const quiz        = job.quiz;
  const hasQuiz     = (quiz?.questions?.length || 0) > 0;
  const hasAttempt  = !!quiz?.completedAt;
  const scorePercent = hasAttempt && quiz.totalQuestions > 0
    ? Math.round((quiz.score / quiz.totalQuestions) * 100)
    : null;

  return (
    <div className="space-y-5 max-w-xl">
      {hasQuiz ? (
        <div className="bg-white border-2 border-nb-black p-5" style={{ borderRadius: '8px', boxShadow: '4px 4px 0 #111' }}>
          <div className="flex items-center justify-between mb-4">
            <div>
              <p className="font-black text-sm uppercase tracking-wide">Quiz Ready</p>
              <p className="text-xs text-nb-black/50 mt-0.5">
                {quiz.questions.length} questions · Technical, HR & Role-specific
              </p>
            </div>
            {scorePercent != null && <ScoreRing score={scorePercent} label="Last Score" size={70} />}
          </div>

          {hasAttempt && (
            <div className="border-2 border-nb-black/15 p-3 mb-4" style={{ borderRadius: '6px' }}>
              <p className="text-[10px] font-black uppercase tracking-widest text-nb-black/40 mb-2">Last Attempt</p>
              <div className="flex flex-wrap gap-4 text-sm">
                <span><span className="font-black">{quiz.score}</span>/{quiz.totalQuestions} correct</span>
                {quiz.categoryScores && Object.entries(quiz.categoryScores).map(([k, v]) => (
                  <span key={k} className="text-nb-black/50 capitalize">{k}: {v}%</span>
                ))}
              </div>
              {quiz.weakAreas?.length > 0 && (
                <div className="mt-2 flex flex-wrap gap-1.5">
                  <span className="text-[10px] font-black uppercase text-nb-black/40 mr-1">Weak areas:</span>
                  {quiz.weakAreas.map(a => (
                    <span key={a} className="text-[10px] font-bold px-1.5 py-0.5 bg-red-100 text-red-700 border border-red-300 capitalize" style={{ borderRadius: '2px' }}>{a}</span>
                  ))}
                </div>
              )}
            </div>
          )}

          <div className="flex gap-3 flex-wrap">
            <button onClick={() => navigate(`/quiz/${job._id}`)} className="btn btn-primary">
              <HelpCircle className="w-4 h-4" />
              {hasAttempt ? 'Retake Quiz' : 'Start Quiz'}
            </button>
            <ActionBtn onClick={generate} loading={loading} variant="ghost">
              <RefreshCw className="w-3.5 h-3.5" /> Regenerate
            </ActionBtn>
          </div>
        </div>
      ) : (
        <div className="max-w-md space-y-4">
          <p className="text-sm text-nb-black/60 leading-relaxed">
            Generate 30–40 MCQ questions tailored to this job description. Covers technical concepts, HR/behavioral questions, and role-specific scenarios. Attempt anytime.
          </p>
          <ActionBtn onClick={generate} loading={loading}>
            <Zap className="w-4 h-4" /> Generate Quiz
          </ActionBtn>
        </div>
      )}
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   MAIN PAGE
═══════════════════════════════════════════════════════════════════════════ */
export default function JobWorkspace() {
  const { id }    = useParams();
  const navigate  = useNavigate();
  const [job,     setJob]     = useState(null);
  const [loading, setLoading] = useState(true);
  const [tab,     setTab]     = useState('overview');

  useEffect(() => {
    api.get(`/jobs/${id}`)
      .then(r => setJob(r.data?.data || r.data?.job || r.data))
      .catch(() => { toast.error('Job not found'); navigate('/jobs'); })
      .finally(() => setLoading(false));
  }, [id, navigate]);

  // Deep merge — handles nested objects like tailoredResume, coverLetter, skillGap
  const handleJobUpdate = useCallback((updated) => {
    if (!updated) return;
    setJob(prev => {
      if (!prev) return updated;
      const merged = { ...prev };
      Object.entries(updated).forEach(([k, v]) => {
        if (v !== null && typeof v === 'object' && !Array.isArray(v) && typeof prev[k] === 'object' && prev[k] !== null && !Array.isArray(prev[k])) {
          merged[k] = { ...prev[k], ...v };
        } else {
          merged[k] = v;
        }
      });
      return merged;
    });
  }, []);

  if (loading) return (
    <DashboardLayout>
      <div className="flex items-center justify-center h-64">
        <Loader2 className="w-8 h-8 animate-spin text-nb-black/30" />
      </div>
    </DashboardLayout>
  );

  if (!job) return null;

  const tabContent = {
    overview:    <OverviewTab    job={job} onTabChange={setTab} />,
    resume:      <ResumeTab      job={job} onJobUpdate={handleJobUpdate} />,
    ats:         <ATSTab         job={job} onJobUpdate={handleJobUpdate} />,
    skills:      <SkillsTab      job={job} onJobUpdate={handleJobUpdate} />,
    tailor:      <TailorTab      job={job} onJobUpdate={handleJobUpdate} />,
    coverletter: <CoverLetterTab job={job} onJobUpdate={handleJobUpdate} />,
    quiz:        <QuizTab        job={job} onJobUpdate={handleJobUpdate} navigate={navigate} />,
  };

  return (
    <DashboardLayout>
      <div className="max-w-5xl space-y-6">

        {/* Header */}
        <div className="border-b-3 border-nb-black pb-5">
          <Link to="/jobs" className="inline-flex items-center gap-1 text-xs font-bold text-nb-black/40 hover:text-nb-black mb-3 transition-colors">
            <ChevronLeft className="w-3.5 h-3.5" /> All Jobs
          </Link>
          <div className="flex items-start justify-between gap-4">
            <div>
              <h1 className="font-black text-nb-black" style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(1.25rem,3vw,2rem)', letterSpacing: '-0.03em' }}>
                {job.title}
              </h1>
              {job.company && <p className="text-sm text-nb-black/45 font-mono mt-0.5">{job.company}</p>}
            </div>
            <div className="flex items-center gap-4 flex-shrink-0">
              {job.atsScore != null && (
                <div className="text-center">
                  <p className={`text-2xl font-black font-mono leading-none ${scoreColor(job.atsScore)}`}>{job.atsScore}</p>
                  <p className="text-[9px] font-black uppercase tracking-widest text-nb-black/40 mt-0.5">ATS</p>
                </div>
              )}
              {job.readinessScore != null && (
                <div className="text-center">
                  <p className={`text-2xl font-black font-mono leading-none ${scoreColor(job.readinessScore)}`}>{job.readinessScore}</p>
                  <p className="text-[9px] font-black uppercase tracking-widest text-nb-black/40 mt-0.5">Ready</p>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex overflow-x-auto border-2 border-nb-black bg-white" style={{ borderRadius: '6px', boxShadow: '3px 3px 0 #111' }}>
          {TABS.map(({ id: tid, label, icon: Icon }) => (
            <button
              key={tid}
              onClick={() => setTab(tid)}
              className={`flex items-center gap-1.5 px-3 py-2.5 text-xs font-black uppercase tracking-wide whitespace-nowrap border-r-2 border-nb-black last:border-r-0 transition-colors flex-shrink-0 ${
                tab === tid ? 'bg-nb-yellow text-nb-black' : 'text-nb-black/50 hover:bg-nb-yellow/20 hover:text-nb-black'
              }`}
            >
              <Icon className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">{label}</span>
            </button>
          ))}
        </div>

        {/* Tab content */}
        <div>{tabContent[tab]}</div>

      </div>
    </DashboardLayout>
  );
}
